"""
LLM-based detection signal via Groq (llama-3.3-70b-versatile).

Sends the submitted text to the model with a structured prompt asking it to
reason about whether the writing reads as human-authored or AI-generated.
Returns a probability score 0.0 (definitely human) to 1.0 (definitely AI)
plus a rationale string.
"""

import os
import json
import re
from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY environment variable not set")
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an expert forensic analyst specializing in distinguishing human-written text from AI-generated text. Your job is to analyze creative writing submitted to an attribution platform.

You will be given a piece of text. Analyze it carefully for indicators of whether it was written by a human or generated by an AI tool.

Indicators of AI-generated text include:
- Overly smooth, consistent prose with no personality quirks
- Predictable paragraph transitions ("Furthermore", "In addition", "Moreover")
- Uniform sentence rhythm and length
- Balanced, hedged language without strong personal voice
- Generic emotional language without specific grounding
- Clean, perfectly structured arguments
- Lack of idiosyncrasy, typos, or natural thought tangents

Indicators of human-written text include:
- Idiosyncratic phrasing or unusual word choices
- Structural imperfections or tangential thoughts
- Inconsistent formality or register shifts
- Strong, specific personal voice
- Emotionally grounded, specific details
- Natural messiness in argument structure

Respond with ONLY a valid JSON object in this exact format:
{
  "ai_probability": <float between 0.0 and 1.0>,
  "rationale": "<2-3 sentence explanation of your reasoning>",
  "key_indicators": ["<indicator 1>", "<indicator 2>", "<indicator 3>"]
}

Where ai_probability:
- 0.0–0.15: Almost certainly human-written
- 0.16–0.35: Likely human-written
- 0.36–0.64: Uncertain / mixed signals
- 0.65–0.84: Likely AI-generated
- 0.85–1.0: Almost certainly AI-generated

Be calibrated. Most real human writing is messy and imperfect. Only give high AI scores when you see clear, consistent AI fingerprints throughout the text."""


def analyze(text: str) -> dict:
    """
    Classify text using Groq LLM and return structured result.

    Returns dict with:
      score (float 0–1, AI probability)
      rationale (str)
      key_indicators (list of str)
      model (str)
      error (str, only if failed)
    """
    if not text or len(text.strip()) < 10:
        return {
            "score": 0.5,
            "rationale": "Text too short for reliable LLM analysis.",
            "key_indicators": [],
            "model": "llama-3.3-70b-versatile",
            "error": "input_too_short",
        }

    truncated_text = text[:4000]  # Stay well within context limits

    try:
        client = _get_client()
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": f"Analyze this text for AI vs. human authorship:\n\n---\n{truncated_text}\n---",
                },
            ],
            temperature=0.1,
            max_tokens=512,
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

        parsed = json.loads(raw)
        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))  # clamp

        return {
            "score": round(score, 4),
            "rationale": parsed.get("rationale", ""),
            "key_indicators": parsed.get("key_indicators", []),
            "model": "llama-3.3-70b-versatile",
        }

    except json.JSONDecodeError as e:
        return {
            "score": 0.5,
            "rationale": "LLM returned unparseable response.",
            "key_indicators": [],
            "model": "llama-3.3-70b-versatile",
            "error": f"json_parse_error: {str(e)}",
        }
    except Exception as e:
        return {
            "score": 0.5,
            "rationale": "LLM analysis unavailable.",
            "key_indicators": [],
            "model": "llama-3.3-70b-versatile",
            "error": str(e),
        }
