"""
Confidence scoring and transparency label generation.

Combines Signal 1 (LLM) and Signal 2 (Stylometric) into a single AI-probability
and a human-readable confidence score, then selects and populates the appropriate
transparency label variant.
"""

# Base weights: LLM captures semantic/holistic patterns (stronger signal);
# stylometrics capture structural fingerprints (reliable but narrower).
LLM_WEIGHT_BASE = 0.60
STYLE_WEIGHT_BASE = 0.40

# Thresholds chosen to be asymmetric: require stronger evidence for AI label
# than for human label, because false positives harm creators more.
HIGH_AI_THRESHOLD = 0.71     # above this → "High-confidence AI"
HIGH_HUMAN_THRESHOLD = 0.29  # below this → "High-confidence human"
# Everything between 0.29 and 0.71 → "Uncertain"


def _dynamic_weights(word_count: int) -> tuple[float, float]:
    """
    Adjust signal weights based on stylometric reliability.

    The stylometric signal needs enough sentences and words to compute
    meaningful variance and diversity statistics. Below ~60 words it has
    too little data and tends to produce inflated AI scores (because short
    texts have few sentences → low SLV, which looks AI-like regardless of
    actual authorship).

    word_count ranges → (llm_weight, style_weight):
      < 40 words   : 0.90 / 0.10  — stylometrics nearly useless
      40–79 words  : 0.75 / 0.25  — stylometrics weakly informative
      80–149 words : 0.65 / 0.35  — stylometrics moderately informative
      150+ words   : 0.60 / 0.40  — full weights, stylometrics reliable
    """
    if word_count < 40:
        return 0.90, 0.10
    if word_count < 80:
        return 0.75, 0.25
    if word_count < 150:
        return 0.65, 0.35
    return LLM_WEIGHT_BASE, STYLE_WEIGHT_BASE


def combine_scores(llm_score: float, style_score: float, word_count: int = 999) -> dict:
    """
    Combine two signal scores into a final AI-probability and confidence value.

    word_count is used to adjust stylometric weight dynamically — the
    stylometric signal is unreliable on short texts and should cede more
    influence to the LLM when fewer than ~80 words are present.

    confidence = how certain the system is, regardless of direction.
    A score of 0.5 → confidence 0.0 (maximally uncertain).
    A score of 0.0 or 1.0 → confidence 1.0 (maximally certain).
    """
    llm_w, style_w = _dynamic_weights(word_count)
    combined = round(llm_w * llm_score + style_w * style_score, 4)
    confidence = round(abs(combined - 0.5) * 2, 4)
    return {
        "ai_probability": combined,
        "confidence": confidence,
        "weights_used": {"llm": llm_w, "style": style_w},
    }


def classify(ai_probability: float) -> str:
    """Return one of: 'ai', 'human', 'uncertain'."""
    if ai_probability >= HIGH_AI_THRESHOLD:
        return "ai"
    if ai_probability <= HIGH_HUMAN_THRESHOLD:
        return "human"
    return "uncertain"


def build_label(ai_probability: float, confidence: float) -> dict:
    """
    Generate the transparency label shown to platform readers.

    Returns a dict with:
      variant: "high_ai" | "high_human" | "uncertain"
      label_text: the verbatim text shown to the user
      ai_pct: integer percentage used in label text
      conf_pct: integer confidence percentage used in label text
    """
    result = classify(ai_probability)
    ai_pct = round(ai_probability * 100)
    conf_pct = round(confidence * 100)

    if result == "ai":
        variant = "high_ai"
        label_text = (
            f"AI-Generated Content — Our analysis strongly suggests this content was "
            f"generated by an AI tool (AI likelihood: {ai_pct}%, confidence: {conf_pct}%). "
            f"Two independent signals — language pattern analysis and writing style statistics — "
            f"both indicate AI authorship. If you are the human author of this work, you can "
            f"submit an appeal and provide additional context. Appeals are reviewed by our "
            f"moderation team."
        )
    elif result == "human":
        variant = "high_human"
        label_text = (
            f"Human-Written Content — Our analysis indicates this content was written by a "
            f"human (AI likelihood: {ai_pct}%, confidence: {conf_pct}%). Both our language "
            f"analysis and writing style statistics support this attribution. This label reflects "
            f"the current state of our analysis and may not be perfect."
        )
    else:
        variant = "uncertain"
        label_text = (
            f"Attribution Unclear — Our analysis found mixed signals and cannot confidently "
            f"determine whether this content was written by a human or generated by AI "
            f"(AI likelihood: {ai_pct}%, confidence: {conf_pct}%). We are not making a "
            f"definitive claim. If you are the author, you may submit an appeal to provide "
            f"context about your creative process."
        )

    return {
        "variant": variant,
        "result": result,
        "label_text": label_text,
        "ai_pct": ai_pct,
        "conf_pct": conf_pct,
    }
